name: 🛠️ Feature request
description: Suggest an idea to improve pageplug
title: "[Feature]: "
labels: [Enhancement]
assignees:
- Nikhil-Nandagopal
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to request a feature for PagePlug!
- type: textarea
  attributes:
    label: Summary
    description: One paragraph description of the feature.
  validations:
    required: true

